services:
  web:
    build: .
    container_name: national_id_web
    volumes:
      - .:/app
        - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
